apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-app-backend-logs
  labels:
    app.kubernetes.io/name: sample-app
    app.kubernetes.io/component: sample-app-backend

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: local-path

  resources:
    requests:
      storage: 2Gi
