apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-app-backend-service-account
  labels:
    app.kubernetes.io/name: sample-app
    app.kubernetes.io/component: sample-app-backend

automountServiceAccountToken: false

imagePullSecrets:
  - name: sample-app-image-pull-secret
