apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-app-admin-service-account
  labels:
    app.kubernetes.io/name: sample-app
    app.kubernetes.io/component: sample-app-admin

automountServiceAccountToken: false

imagePullSecrets:
  - name: sample-app-image-pull-secret
