apiVersion: v1
kind: Service
metadata:
  name: sample-app-admin
  labels:
    app.kubernetes.io/name: sample-app
    app.kubernetes.io/component: sample-app-admin

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: sample-app
    app.kubernetes.io/component: sample-app-admin

  ports:
    - name: http
      port: 3004
      targetPort: http
      protocol: TCP
