apiVersion: v1
kind: Service
metadata:
  name: sample-app-redis
spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: sample-app
    app.kubernetes.io/component: sample-app-redis

  ports:
    - name: redis
      port: 6379
      targetPort: redis
      protocol: TCP
