services:
  ## ------------------------- ##
  ## PostgreSQL Database Setup ##
  ## ------------------------- ##
  postgresDB:
    image: postgres:latest # Official PostgreSQL image
    container_name: postgresDB # Custom container name for easier reference
    restart: always # Ensures the container restarts on failure
    ports:
      - "5432:5432" # Maps host port 5432 to container port 5432 (PostgreSQL default)
    environment:
      POSTGRES_USER: webapp # Username for PostgreSQL authentication
      POSTGRES_PASSWORD: webappPass@donotshare # Password for the database user (Secure this in production)
      POSTGRES_DB: webappDB # Default database created on startup
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persistent volume for database storage
    networks:
      - db-network # Network for connecting to database-related services
      - backend-network # Network for backend services to access the database

  ## ------------------------- ##
  ## memcached Setup ##
  ## ------------------------- ##
  memcached:
    image: memcached:latest
    container_name: memcached
    restart: always
    ports:
      - "11211:11211"
    networks:
      - backend-network

## ------------------- ##
## Network Definitions ##
## ------------------- ##
networks:
  db-network:
    driver: bridge # Isolated network for database communication
  frontend-network:
    driver: bridge # Isolated network for frontend services (if needed)
  backend-network:
    driver: bridge # Network for backend services to communicate with the database

## ----------------- ##
## Volume Definition ##
## ----------------- ##
volumes:
  postgres-data: # Persistent storage for PostgreSQL to retain data across container restarts
