FROM node:24-alpine AS deps

WORKDIR /backend

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn

RUN corepack enable
RUN yarn install --immutable


FROM node:24-alpine AS builder

WORKDIR /backend

COPY --from=deps /backend/node_modules ./node_modules
COPY . .

RUN corepack enable
RUN yarn build


FROM node:24-alpine AS runner

WORKDIR /backend

ENV NODE_ENV=production
# Create non-root user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn

RUN corepack enable
RUN yarn workspaces focus --production



# Remove package managers from final runtime image
RUN rm -rf /usr/local/lib/node_modules/npm \
    /usr/local/bin/npm \
    /usr/local/bin/npx \
    /usr/local/lib/node_modules/corepack \
    /usr/local/bin/corepack

COPY --from=builder --chown=appuser:appgroup  /backend/build ./build

EXPOSE 5009

USER appuser

CMD ["node", "build/index.js"]