apiVersion: v1
kind: Secret
metadata:
  name: sample-app-dev-db-owner
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: sample_app_user
  password: CHANGE_ME_TO_A_STRONG_PASSWORD
