apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default-deny-ingress.yml
  - allow-backend-to-postgres.yml
  - allow-backend-to-redis.yml
  - allow-ingress-nginx-to-admin.yml
